version: '3'

services:
  app:
    image: onboard-back-end
    container_name: onboard-back-end
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "4000:4000"
    expose:
      - 4000
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongodb
    networks:
      - onboard-back-end
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - onboard-back-end
    volumes:
      - db:/data/db
networks:
  onboard-back-end:
volumes:
  db:
